openapi: '3.0.3'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
servers:
  - url: 'http://localhost:9090/api'
tags:
  - name: Menus-end-point
    description: Gestion des menus
paths:
  /menus:
    get:
      tags:
        - Menus-end-point
      summary: Obtient une liste de toutes les menus
      operationId: getMenus
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Menu'
        '404':
          description: Not Found
    post:
      tags:
        - Menus-end-point
      summary: Ajoute une nouvelle menu
      operationId: addMenu
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Menu'
      responses:
        '201':
          description: menu crée
          headers:
            Location:
              description: URL de la menu crée
              schema:
                type: string
                format: uri
  /menus/{id}:
    get:
      tags:
        - Menus-end-point
      summary: Obtient une menu
      operationId: getMenu
      parameters:
        - name: id
          in: path
          description: numéro de la menu à obtenir
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Menu'
        '404':
          description: Not Found
      deprecated: false
components:
  schemas:
    Menu:
      description: toutes les caractéristiques d'une menu
      type: object
      properties:
        author:
          description: nom de l'auteur
          type: string
        citation:
          description: phrase de la citation
          type: string
        id:
          description: numéro auto-incrémenté de la citation
          type: integer
          format: int32
      title: Menu
